### ISSUE TITLE
Incompatible with Nengo 3

### ISSUE THREAD

**Issue by jgosmann** [nengo-labs/nengo-ocl#165] opened 2020-02-08 15:08 UTC
Using Nengo 3, `import nengo_ocl` fails with:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-9-cb83d6532822> in <module>
----> 1 import nengo_ocl

~/Library/Python/3.7/lib/python/site-packages/nengo_ocl/__init__.py in <module>
      5 import pyopencl as cl
      6 
----> 7 from nengo.utils.logging import log
      8 
      9 from .version import version as __version__

ModuleNotFoundError: No module named 'nengo.utils.logging'
```

**Comment by drasmuss** [comment] 2020-02-18 16:10
Yeah this is on our TODO list to fix, but unfortunately probably won't happen in the near term just because our resources are focused on other Nengo backends at the moment.

**Comment by MPnoy** [comment] 2020-06-11 05:59
What should users do now? The first thing to do when moving on to the practical use of some kind of computing framework is to make it work on the GPU, not the CPU, without this feature nengo is not very useful for any large models.

**Comment by drasmuss** [comment] 2020-06-11 12:41
You can use [NengoDL](https://www.nengo.ai/nengo-dl/) to run any Nengo model on a GPU. It is compatible with nengo 3.

**Comment by tcstewar** [comment] 2020-06-11 14:44
Do we have speed comparisons between NengoOCL and NengoDL?  If they are similar in speed, then should we consider retiring NengoOCL and directing people towards that?

Otherwise, the main thing would be to add some clear instructions as to how to switch back to Nengo 2.8 until NengoOCL is updated to support Nengo 3.0.  This should be just `pip install nengo==2.8`.

**Comment by arvoelke** [comment] 2020-06-11 15:00
There are [quite a few flags] (https://www.nengo.ai/nengo-dl/tips.html#speed-improvements) you can tweak to optimize speed in Nengo-DL which makes comparisons a bit tricky. Nengo-DL also supports input batching. But in the experiments that I've done with just a single input I've found that Nengo-DL models with factored weight matrices need to be set to 32 bit to achieve the same performance as Nengo-OCL, while full (all-to-all matrices) were faster on Nengo-DL with either 32 or 64 bits. But this was just one kind of network, and there could easily be hidden factors such as choice of GPU, neuron models, versions of Tensor flow, CUDA, etc..

**Comment by atait** [comment] 2020-07-08 01:52
Hi there,

I've used nengo for about 5 years for neuromorphic hardware research. First time GPU for scientific computing user. My interest is to accelerate my and colleagues' dev environments for eventual Loihi/SpiNNaker deployments, nothing do with deep learning. It needs to work easily on multiple personal and datacenter machines and port to multiple neuromorphic backends.

I performed both installations and examples of nengo-ocl and nengo-dl. I sense that Nengo DL is the wrong way to meet these interests and that there is reason for nengo OCL to exist as a complement to nengo DL.

1. DL does not completely satisfy the "backend" abstraction
2. DL is harder to get started cross-platform
3. DL trades maintainability for performance

Performance is a totally valid priority. So is maintainability and cross-platform ease of use. Hence, two different packages.

### Rationale
It looks like Nengo DL requires significant changes to end-user code (e.g. `Ensembles` -> `TensorNodes`) in order to really take advantage of the GPU. This not only renders existing code obsolete; it makes new code more difficult to map to Loihi, SpiNNaker, TrueNorth, etc. This departs from the abstraction of different "backends" and identical "frontends."

It was much easier to achieve the packaged benchmarks using nengo OCL. On a fresh Ubuntu, it's just `apt`, `pip`, and reboot to arrive at a 30x speedup on the OCL "`benchmark_circconv`". On the other hand, it took me a full day, multiple partially-applicable installer guides, proprietary installers, [install sequence-dependent environment states](https://forum.nengo.ai/t/install-nengo-dl-for-gpu/724), and an NVIDIA developer account to get 20x speedup on the DL "`spiking_mnist`" test.

Nengo DL depends on a lot of bleeding edge software: TF->CuDNN->CUDA->NVIDIA. This development philosophy is good for performance and bad for maintanability. All of those things are actively releasing new and [mutually incompatible versions](https://github.com/tensorflow/tensorflow/issues/40227). At one point, TF lagged behind python 3.7 (*python*!), and [everyone had to figure out how to rollback python](https://www.google.com/search?client=ubuntu&channel=fs&sxsrf=ALeKk00liUeOW277idDSNKtSjiXFRmbccg%3A1594148986602&ei=esgEX5upJIyx0PEPs5-_-As&q=how+to+rollback+python+3.7+tensorflow&oq=how+to+rollback+python+3.7+tensorflow&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQRzIECAAQR1AAWABgklZoAHAEeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwibzsLg67vqAhWMGDQIHbPPD78Q4dUDCAs&uact=5). At the time of writing, TF requires [rollback to CUDA 10.1](https://github.com/tensorflow/tensorflow/issues/40227), which in turn requires a rollback to g++ 8.4 (*g++*!). None of them are officially tested on Ubuntu 20.04. Forget about using a non-NVIDIA GPU. One partial remedy could be Docker, but does Docker work down to the lowest driver levels?

Getting highest performance on DL is attractive but places a burden on nengo developers to keep up to date with that stack. OCL could take a complementary philosopy of maintainability over performance, and so I think a one-time development effort to Nengo 3.1 could be justified in that way.

### Some benchmarking results
- my hardware
    - Ubuntu 20.04 Focal Fossa
    - Intel i5-6400, quad-core, 2.4GHz
    - NVIDIA GeForce GTX970 4GB
    - NVIDIA driver 440.1
    - CUDA 10.1.105
    - OpenCL 2.1
- `nengo-ocl/examples/benchmark_circconv.py`, 1024 dimensions
    - `nengo.Simulator` w/ nengo 2.8.0 or 3.1.0.dev0
        - run time 66 sec
        - build time 170 sec
        - results correct
    - `nengo_ocl.Simulator` w/ nengo 2.8.0
        - run time 2.5 sec
        - build time similar to above
        - results correct
    - atait-branch:`nengo_ocl.Simulator` w/ nengo 3.1.0.dev0
        - run time similar to above
        - build time similar to above
        - *results very incorrect*
    - `nengo_dl.Simulator` w/ nengo 3.1.0.dev0
        - run time 8.0 sec
        - build time 374 sec
        - results correct
- `nengo-dl/spiking_mnist.ipynb`, call to `sim.evaluate` before training
    - `nengo_dl.Simulator(..., device='/cpu:0')`: wall time 610 sec
    - `nengo_dl.Simulator(..., device='/gpu:0')`: wall time 32 sec
    - `nengo.Simulator`: incompatible
    - `nengo_ocl.Simulator`: incompatible

I didn't try too hard to configure DL, just used the drop-in Simulator. Out of the box, it does simulate faster, but it does not match OpenCL on circconv, and its build time is much longer. Does anyone want to try this with DL with the configure options?

I also tried dropping nengo_dl.Simulator into my existing library code, and it ran slower than the original.

### Brief attempt at Nengo OCL for Nengo 3
I have started a branch on my fork off of nengo/nengo-ocl : master

https://github.com/atait/nengo-ocl : nengo3

It runs; it passes all but one test; however, there is still a bug in correctness of results. I will need some help to go further.

#### The easy changes
- Stripping python 2
    - replace all `compat` components (is_iterable, is_number, etc.)
    - xrange to range
    - `np.asarray` to `np.fromiter`

- Use `make_state`
    - This is now needed before `make_step`

- Simple renaming
    - `ProbeDict` to `SignalDict`
    - `allclose` to `signals_allclose`

- Testing
    - get `pytest-allclose`, `pytest_rng`, and `pytest_plt` from new locations
    - disabled logging or substituted `capsys` from pytest
        - TODO: use pytest to restore full logging
    - removed `--simulator` and `--reference-simulator` from tox.ini
    - removed `-p nengo.tests.options` from tox.ini
        - The pytest `addopts` from `pytest_nengo.py` are being discovered automatically. I'm not exactly sure how it is finding those. You have to be careful that `pytest_nengo.py` is not double-installed in the system and the nengo source.

#### State-space filter
This [PR](https://github.com/nengo/nengo/pull/1535) is a big upgrade in efficiency and accuracy from @hunse and requires some significant changes to OCL

- The v2.8 `make_step` does some preprocessing of num and den, so that code needed to be copied over

- Nengo OCL is expecting to get numerators and denominators, so I used `ss2tf` to recover them from the new representation. It also wanted types `NoDen` and `Simple` instead of the new `NoX`, `NoD`, etc.
    - Behavior on Alpha response is patchy because it is 2-pole, so
    - I think my solution to this will fail in the general case
    - __quick solution__ is to debug my array handling `Simulator._plan_linearfilter`
    - __good solution__ would be to write a new `plan_linearfilter` for state-space calculations. I don't know how to write that GPU code.

- Subtle change to `make_step` interface:

See my changes to `test_clra_nonlinearities.py:test_linearfilter` for reference. The OCL test there works vs. the 2.8 version, but I had to *change the reference simulation* in the following ways to pass the test in 3.1
    - `size_in=(n,1)` is now `size_in=(n,)`
    - to get an input ndarray `x` from RaggedArray `X` now involves a transpose
    - In other words, the nengo 3.0 API might have swapped some dimensions on input and output (unless I am missing something), and the OCL API should change with it: TODO

#### Planner
Comparing the `greedy_planner.op_groups` attribute from OCL to the `Simulator.step_order` from nengo core gives different results. There is no longer an `ElementwiseInc`; there are new operations related to PES; there is some reordering of the copys. This makes a test of `assert len(sim.op_groups == 9)` fail, but it's unclear whether that matters. I'm stuck.

### Thoughts?
I'm not aware of the whole nengo ecosystem. To those who do, does this make any sense?

There's also a good chance that I'm missing something simple about nengo DL that would make backend portability easier and performance better. Is it as simple as
```python
nengo.Ensemble = nengo_dl.TensorNode
# rest of code developed for original nengo
```
?

In regards of eventually porting to multi-GPU cloud instances, is this supported via OpenCL or only by CUDA?

Thanks for reading

**Comment by arvoelke** [comment] 2020-07-08 02:46
Thanks for the thoughtful post @atait and especially looking into supporting Nengo 3 with your fork and the details in the changes you had to make. Personally I think this would be great to make into a PR (not that I would be the one to review it however). But in the interest in providing a quick response, I'd like to reply to these parts:

> It looks like Nengo DL requires significant changes to end-user code (e.g. Ensembles -> TensorNodes) in order to really take advantage of the GPU. This not only renders existing code obsolete; it makes new code more difficult to map to Loihi, SpiNNaker, TrueNorth, etc. This departs from the abstraction of different "backends" and identical "frontends."
>
> It was much easier to achieve the packaged benchmarks using nengo OCL. On a fresh Ubuntu, it's just apt, pip, and reboot to arrive at a 30x speedup on the OCL "benchmark_circconv". On the other hand, it took me a full day, multiple partially-applicable installer guides, proprietary installers, install sequence-dependent environment states, and an NVIDIA developer account to get 20x speedup on the DL "spiking_mnist" test.
> ...
> I'm not aware of the whole nengo ecosystem. To those who do, does this make any sense?
> There's also a good chance that I'm missing something simple about nengo DL that would make backend portability easier and performance better.

It isn't the case that NengoDL requires changing the code (e.g.` Ensemble` -> `TensorNode`) in order to take advantage of the GPU. The critical piece that I feel might be missing from reading this is that you can simply take that example benchmark for NengoOCL (`examples/benchmark_circconv.py`) and replace `nengo_ocl.Simulator` with `nengo_dl.Simulator`, and then omit the OpenCL context. No other changes are needed. To be concrete, you can add this `elif` block to the benchmark and then use the `dl` argument instead of `ref` or `ocl`:

```python
elif sys.argv[1] == 'dl':
    import nengo_dl
    sim_name = 'dl' if len(sys.argv) == 3 else sys.argv[3]
    sim_class = nengo_dl.Simulator
    sim_kwargs = {}
```

The MNIST benchmark that you chose for NengoDL is making use of additional TensorFlow features that you don't need. If all you want to do is build models that are simulatable with Nengo or NengoOCL, then it's a matter of restricting yourself to that subset of the API (i.e., avoiding the `TensorNode` you mentioned). In other words, you can think of NengoDL as a superset of NengoOCL (this isn't true in a strict sense, but it's useful conceptually and for discussion).

In practice, this means that, for any model you are currently simulating with Nengo or NengoOCL, you should be able to swap out the `nengo.Simulator` or `nengo_ocl.Simulator` for `nengo_dl.Simulator`. Let us know if you find any situations where this is not the case, or if you see a degradation in performance, other constraints, or any reason to prefer one over the other in this case where you aren't requiring the added features of TensorFlow. We'd like to know, and I wouldn't be surprised if there were a few subtleties here!

With respect to issues with TensorFlow installations and conflicting versions, personally, I'd highly recommend using [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html). Once you install that and create+activate an environment, you should be able to run `conda install tensorflow-gpu` and get all of the correct versions for your system, including a dynamically linked CUDA library. I've never had any issues going this route over the past few years. The only issues I've had here have been related to nvidia drivers falling out of date, but that has been a once-a-year kind of occurrence for me. Hope this helps.

**Comment by atait** [comment] 2020-07-08 18:59
Thanks @arvoelke! 

I did do that elif block in my benchmarking above^. nengo_dl/TF/CUDA performed better than CPU but noticably slower than nengo_ocl/OpenCL. I considered that to be not taking full advantage of the GPU. Could this be explained by some opt-out features in nengo_dl (e.g. trainability?) that must be deactivated to make a fairer comparison? 

I understand that `nengo_dl.Simulator` is meant to be a drop-in just like `nengo_cl.Simulator`. It does work correctly and with speedup, so my "not satisfying backend abstraction" was probably an overstatement. The large increase in DL build time was a little concerning. Suppose you had model that was built/optimized with standard nengo: could nengo_dl drop-in on that? Could nengo_ocl?

- example use case: building on local PC, pickling model, simulating on cloud instance

My long setup time was due to inexperience with GPUs. I will try conda next time. Do you think the nengo.ai/nengo_dl/installation.html documentation might benefit from something more than `pip install tensorflow-gpu`? It could just be a note saying that one will need to find a way to get CuDNN, CUDA, and the low-level drivers.

As for a nengo 3 PR to nengo_ocl, I'm still not sure if it's worth it. It seemed not too bad, but it's unclear to me whether those two sticking points:

- state-space filter implementation
- operation planning strategy

are minutes or days worth of work. Who would be able to assess that?

Long term, nengo_ocl might serve as a lightweight introductory and/or fallback option. On a freshly installed OS, it's really just
```bash
sudo apt install python3.8 nvidia-driver-440 ocl-icd-opencl-dev opencl-headers
# reboot
pip3 install --no-use-pep-517 pyopencl
pip3 install nengo-ocl
```
and you're off playing with a GPU. I don't think it needs to keep pace with future development, so maybe nengo_ocl could exist but throw a "not maintained" warning. That's really up to your team. Short term, it would be nice to get it in nengo 3 to do some more benchmarking.

**Comment by drasmuss** [comment] 2020-07-08 21:10
> Could this be explained by some opt-out features in nengo_dl (e.g. trainability?) that must be deactivated to make a fairer comparison?

Yes you would want to do `nengo_dl.configure_settings(inference_only=True)` at the minimum. And there are a number of other flags you can play with if you really want to customize the performance to your needs, see https://www.nengo.ai/nengo-dl/tips.html#speed-improvements for more details.

Another thing to keep in mind is that the way TensorFlow works, the graph doesn't get fully built/optimized until the first timestep. So if you just start timing from the first call to `sim.run`, you're actually measuring a lot of build time in addition to run time. If you just want to assess the run speed, you can do a "warmup run" ahead of time, like
``` python
sim.run(0.1)

# < start timing >
sim.run(...)
# < stop timing >
```
You can check out the benchmarking scripts here https://github.com/nengo/nengo-dl/blob/master/nengo_dl/benchmarks.py if you like, which have all those details accounted for.

And just for your future ease of use, this is the nengo-dl equivalent to your nengo-ocl installation snippet (assuming you're using `conda`, which as @arvoelke said would be recommended):
```
sudo apt install nvidia-driver-430
# reboot
conda install cudatoolkit=10.1 cudnn
pip install nengo-dl
```

**Comment by atait** [comment] 2020-07-08 22:12
1. Ok `inference_only` is exactly what I was looking for
2. The circconv benchmark already does the warmup you described
3. Excellent install script! 
4. Any comment on the nengo_dl build time I was seeing? Is that fixed by `inference_only`?

**Comment by drasmuss** [comment] 2020-07-09 00:23
> Any comment on the nengo_dl build time I was seeing? Is that fixed by inference_only?

When I run that benchmark using 1024 dimensions I get 

Nengo core:
Build: 356s
Run: 189s

NengoDL:
Build: 472s
Run: 3s

So, a relatively small increase in runtime in NengoDL. We'd always expect some increase, because NengoDL starts by running the Nengo core build process, and then after that has to do the second step of building a TensorFlow graph. I'm not sure why you are seeing such a drastic difference in build time, probably just the weirdness of different systems with different settings that is always hard to control for.

**Comment by atait** [comment] 2020-07-09 09:13
<img width="956" alt="image" src="https://user-images.githubusercontent.com/1455840/87020550-dadf4600-c188-11ea-8646-0d30d6b77ade.png">

For me, OCL is consistently outpacing DL. It is only a factor of 2, and of course this example was designed for OCL. So I'm less concerned about those run times and more puzzled by those build times. I'm most confused about how our nengo core numbers are so different.

**Comment by hunse** [comment] 2020-07-09 15:08
Nengo core build times will depend a lot on your Numpy/BLAS installation (along with CPU power), since it's largely governed by the calculations needed for decoder solving (computing activities, matrix multiply, Cholesky decomposition). Also, you'll want to check whether Nengo is caching solved decoders (which it will do by default if you're using the same seed), since this will speed things up. I'm guessing that in your case, @atait, the decoder cache is making your build faster. You can turn it off with `nengo.rc.set("decoder_cache", "enabled", "False")` right after you `import nengo`.

Back to your original point, I think there is still a place for NengoOCL. It's never been something that we've wanted to drop entirely, but it's been on the backburner for sure; knowing that you're interested in using it and have already put some work into doing the upgrades will definitely help motivate us to get on it more quickly!

My guess is that it's about a week's worth of work to get it working with Nengo 3, particularly if we want to properly implement the state-space filtering as you described. At our next meeting we'll revisit this and see if we can push it higher up the queue.

In the mean time, I've made a `nengo3` branch in this repo. You can make a PR from your `nengo3` branch to merge into this repo's `nengo3` branch. That way, when we're ready to work on this, we can start with what you've got and add on to it to make the final PR that will get merged into master. You will also need to sign the contributor's agreement by making a PR on nengo.github.io to add your name to [this page](https://github.com/nengo/nengo.github.io/blob/master/people.md).

**Comment by atait** [comment] 2020-07-09 23:25
Thanks for making the branch. I'll set up a PR

I did some more benchmarking, but the results were somewhat inconsistent between yesterday and this afternoon. It takes longer even when using the cache. Who knows why... These points are consistent:

- caching has a large effect, and it removes the spread between different BLAS versions (mkl_rt vs. openblas). That's expected.
- Like yesterday, the DL build is between 2x and 3x longer across the board, whether it's python prepackaged 3.7 or source-built+optimized 3.8, cached or not, mkl_rt vs. openblas*, nengo 3.0.0 or nengo 3.1.0.dev0.

_* DL is not touching the GPU during build or warm periods, so I expect it is not using cublas *during the build*. Off topic: has anyone looked into calculating the decoders on GPU?

**Comment by atait** [comment] 2020-08-14 18:33
Sparsity and optimization were huge updates to Nengo 3.0.0 in terms of performance, so I think that's a key aspect of compatibility. I put them in PR #174 against nengo-ocl:nengomaster, so OCL is now compatible with `SparseDotInc` and `BsrDotInc`. It can handle a 1M x 1M weight matrix with about 10M nonzeros on my laptop, and you don't have to choose between sparsity and parallelism.

That's about all that I plan to modify in Nengo OCL. Now that nengo/nengo-dl#160 is solved (thank you for that!), my main research can move to the Volta cluster likely with Nengo DL. That cluster is expensive, so Nengo OCL is going to be important for my lab for developing models on our primarily Intel Iris and AMD devices. Hope others find it useful too.

**Comment by drasmuss** [comment] 2020-08-17 18:12
Nengo 3 compatibility done in #172

**Closed by drasmuss** 2020-08-17 18:12 UTC
